name: Documentation
run-name: Documentation build by ${{ github.actor }}
on:

  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, 'skip docs')"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true

    - name: Install DIALS environment
      run: |
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
        conda create -c conda-forge -y --name dials dials
        conda info
        $CONDA/bin/activate dials

    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[docs]"

    - name: Build documentation
      run: |
        git checkout sphinx
        cd docs
        make clean
        make html
        
    - name: Commit documentation changes to gh-pages
      run: |
        cd docs
        git clone https://github.com/dennisbrookner/matchmaps.git --branch gh-pages --single-branch gh-pages
        cd gh-pages
        cp -r ../_build/html/* .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Upload documentation from latest commit"
    - name: Push changes to gh-pages
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "gh-pages"
        directory: "docs/gh-pages"
