name: Build
run-name: Build by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clean previous build
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox -e clean

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true

    - name: Install DIALS environment
      run: |
        conda create -c conda-forge -y --name dials dials
        conda info
        $CONDA/bin/activate dials

    - name: Build with tox
      run: |
        tox -e build

    - name: Run tests with tox + pytest
      run: |
        tox

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests

    - name: Build documentation with tox
      run: |
        tox -e docs
        tox -e doctests
        tox -e linkcheck

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ github.actor }}@users.noreply.github.com
        message: "Commit built documentation"
        add: "./docs/"
        branch: ${{ github.ref }}
