name: Build
run-name: Build by ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clean previous build
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox -e clean

    - name: Install Miniconda and DIALS
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge, defaults
        use-only-tar-bz2: true
        auto-update-conda: true
        auto-activate-base: true
      run: |
        conda create -c conda-forge -y --name dials dials
        conda activate dials

    - name: Build with tox
      run: |
        tox -e build
