name: Documentation
on: [push]
jobs:
  build:
    runs_on: [ubuntu-latest, macos-latest]
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Clean previous build
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox -e clean

    - name: Build documentation with tox
      run: |
        tox -e docs
        tox -e doctests
        tox -e linkcheck
