name: Format
on: [push]
jobs:
  format:
    runs_on: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Format code with black
        run: |
          pip install black
          black .
      - name: Sort imports with isort
        run: |
          pip install isort
          isort .
      - name: Remove unused imports with autoflake
        run: |
          pip install autoflake
          autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: ${{ github.actor }}
          author_email: ${{ github.actor }}@users.noreply.github.com
          message: "Commit formatting and linting fixes"
          add: "."
          branch: ${{ github.ref }}
