name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  runs-on: ubuntu-latest
  steps:
  - name: Install Python
    uses: actions/checkout@v3
    with:
      python-version: '3.10'
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install packaging setuptools twine wheel typing-extensions tox-conda
  - name: Publish the Python package
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    run: |
      tox -e build
      tox -e docs
      tox -e doctests
      tox -e linkcheck
      tox -e publish
