name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - name: Install Python
      uses: actions/checkout@v3
      with:
        python-version: '3.10'
    - name: Install Miniconda                 
      uses: conda-incubator/setup-miniconda@v2
      with:                                   
        miniconda-version: "latest"           
        channels: conda-forge, defaults       
        auto-activate-base: true              
        activate-environment: ""              
    - name: Install DIALS environment and more       
      run: |                                         
        conda install -n base conda-libmamba-solver  
        conda config --set solver libmamba           
        conda install -n base -c conda-forge -y dials
        $CONDA/bin/pip install -e ".[docs]"          
        cd docs                                      
        export SPHINXBUILD="$CONDA/bin/sphinx-build" 
        make clean                                   
        make html                                    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U setuptools setuptools_scm wheel
        pip install packaging twine typing-extensions tox-conda myst-parser docutils
    - name: Build the Python package
      run: |
        tox -e build
        tox -e docs
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
